name: Build & Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - arch: amd64
            compiler: g++
            strip: strip
          - arch: aarch64
            compiler: g++-aarch64-linux-gnu
            strip: aarch64-linux-gnu-strip

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install compilers and tools
      run: |
        sudo apt update
        # Menambahkan binutils untuk perintah strip
        sudo apt install -y g++ g++-aarch64-linux-gnu binutils-aarch64-linux-gnu zip

    - name: Build binary
      run: |
        mkdir -p build
        ${{ matrix.compiler }} lib/main/main.cpp lib/main/module/banner.cpp lib/main/module/logger.cpp lib/main/module/message.cpp \
        -o build/intipnet \
        -Wall -Wextra -std=c++17 -Iinclude

    - name: Strip binary
      run: ${{ matrix.strip }} build/intipnet

    - name: Create ZIP archive
      run: |
        cd build
        zip intipnet-linux-${{ matrix.arch }}.zip intipnet
        cd ..

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/intipnet-linux-${{ matrix.arch }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
